import { createRouter as createTanStackRouter } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';

// Central router factory. `routeTree.gen.ts` is generated by the TanStack
// Start Vite plugin from the files under `src/routes/`; it does not exist
// until the first `vite dev`/`vite build`.
export function createRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}
